### ISSUE TITLE
Sandbox result has too many closing brackets after `defn`

### ISSUE THREAD

**Issue by joachimdb** [Convex-Dev/issues#1]
![image](https://user-images.githubusercontent.com/1315291/96849341-c97b2a80-1455-11eb-8f55-7392cf713ad2.png)

**Comment by mikera** [comment]
Thanks for the report! That's a bug in the .toString() of a lambda function. Fixed and tested for the next snapshot.

**Comment by deepheap** [comment]
Fixed. Thanks @joachimdb .
